// Netlify Function: "request a copy" for papers whose published version is
// behind a paywall.
//
// A page carries <div class="request-copy" data-doi="10.xxxx/yyyy"></div>.
// assets/request-copy.html turns that into a form that POSTs here. This
// function checks the DOI against data/private_papers.csv, decrypts the
// matching file under private/ with the key in PAPER_KEY, emails the PDF to
// the requester, and emails the owner a notification of the request.
//
// Environment variables (Netlify site configuration > Environment variables):
//   RESEND_API_KEY   API key from resend.com
//   PAPER_KEY        64 hex characters, generated by scripts/encrypt_paper.sh
//   OWNER_EMAIL      where request notifications go
//   FROM_EMAIL       sender, on a domain verified in Resend, e.g. papers@dsimons.org
//
// Files bundled with the function (see netlify.toml included_files):
//   data/private_papers.csv   doi,title,file,iv,attachment_name
//   private/*.pdf.enc         AES-256-CBC ciphertext; the IV is in the CSV

import { readFileSync, existsSync } from "node:fs";
import { createDecipheriv } from "node:crypto";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const config = { path: "/api/request-paper" };

const ALLOWLIST = "data/private_papers.csv";

function findFile(rel) {
  const candidates = [
    resolve(process.cwd(), rel),
    fileURLToPath(new URL("../../" + rel, import.meta.url)),
    resolve("/var/task", rel),
  ];
  return candidates.find((p) => existsSync(p));
}

function loadAllowlist() {
  const path = findFile(ALLOWLIST);
  if (!path) throw new Error("allowlist not bundled");
  const lines = readFileSync(path, "utf8").split(/\r?\n/).filter((l) => l.trim());
  const header = lines.shift().split(",").map((h) => h.trim());
  return lines.map((line) => {
    // Titles may contain commas; they are quoted. Minimal CSV parse.
    const cells = [];
    let cur = "", quoted = false;
    for (const ch of line) {
      if (ch === '"') quoted = !quoted;
      else if (ch === "," && !quoted) { cells.push(cur); cur = ""; }
      else cur += ch;
    }
    cells.push(cur);
    return Object.fromEntries(header.map((h, i) => [h, (cells[i] || "").trim()]));
  });
}

function normDoi(x) {
  return String(x || "").trim().toLowerCase().replace(/^https?:\/\/(dx\.)?doi\.org\//, "").replace(/^doi:\s*/, "");
}

function decrypt(file, ivHex) {
  const path = findFile(file);
  if (!path) throw new Error(`encrypted file not bundled: ${file}`);
  const key = Buffer.from(process.env.PAPER_KEY || "", "hex");
  if (key.length !== 32) throw new Error("PAPER_KEY must be 64 hex characters");
  const iv = Buffer.from(ivHex, "hex");
  if (iv.length !== 16) throw new Error("iv must be 32 hex characters");
  const d = createDecipheriv("aes-256-cbc", key, iv);
  return Buffer.concat([d.update(readFileSync(path)), d.final()]);
}

async function sendEmail(payload) {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });
  if (!res.ok) throw new Error(`email send failed: ${res.status} ${await res.text()}`);
}

function page(title, body, status = 200) {
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}</title>
<style>body{font-family:system-ui,sans-serif;max-width:40rem;margin:4rem auto;padding:0 1rem;line-height:1.5}</style>
</head><body><h1>${title}</h1>${body}<p><a href="javascript:history.back()">Back</a></p></body></html>`;
  return new Response(html, { status, headers: { "Content-Type": "text/html; charset=utf-8" } });
}

export default async (req) => {
  if (req.method !== "POST") return page("Method not allowed", "<p>This endpoint accepts form submissions only.</p>", 405);

  let form;
  try { form = await req.formData(); } catch { return page("Bad request", "<p>Could not read the form.</p>", 400); }

  // Honeypot. Real users never fill the hidden "website" field.
  if (form.get("website")) return page("Sent", "<p>If the address is valid the paper is on its way.</p>");

  const email = String(form.get("email") || "").trim();
  const name = String(form.get("name") || "").trim().slice(0, 120);
  const doi = normDoi(form.get("doi"));

  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return page("Check the email address", "<p>The address does not look valid.</p>", 400);

  const entry = loadAllowlist().find((e) => normDoi(e.doi) === doi);
  if (!entry) return page("Not available", "<p>That paper is not available through this form.</p>", 404);

  const from = process.env.FROM_EMAIL || "papers@dsimons.org";
  const owner = process.env.OWNER_EMAIL;
  if (!process.env.RESEND_API_KEY || !owner) return page("Not configured", "<p>The request service is not configured yet. Please email the author directly.</p>", 500);

  try {
    const pdf = decrypt(entry.file, entry.iv);
    const filename = entry.attachment_name || "paper.pdf";

    await sendEmail({
      from,
      to: [email],
      reply_to: owner,
      subject: `Requested paper: ${entry.title}`,
      text: [
        `Hello${name ? " " + name : ""},`,
        "",
        `Attached is the author copy of "${entry.title}" (https://doi.org/${doi}) that you requested from www.dsimons.org.`,
        "",
        "This copy is for your personal scholarly use. Please cite the published version.",
        "",
        "David Simons",
      ].join("\n"),
      attachments: [{ filename, content: pdf.toString("base64") }],
    });

    await sendEmail({
      from,
      to: [owner],
      subject: `Paper request: ${entry.title}`,
      text: [
        `A copy of "${entry.title}" (${doi}) was sent automatically.`,
        "",
        `Requester: ${name || "(no name)"} <${email}>`,
        `Time: ${new Date().toISOString()}`,
        `Referer: ${req.headers.get("referer") || "unknown"}`,
      ].join("\n"),
    });
  } catch (err) {
    console.error(err);
    return page("Something went wrong", "<p>The paper could not be sent. Please email the author directly.</p>", 500);
  }

  return page("Sent", `<p>The paper has been emailed to <strong>${email.replace(/</g, "&lt;")}</strong>. Check your spam folder if it does not arrive within a few minutes.</p>`);
};
