project:
  type: website

website:
  title: "David Simons"
  favicon: /images/icon.ico
  open-graph: true
  twitter-card: true
  google-analytics: "G-Z4H9BE4MVE"
  page-navigation: true
  navbar:
    logo: /images/icon.ico
    foreground: light
    background: dark
    search: true
    left:
      - href: index.qmd
        text: "{{< iconify mingcute home-2-line >}} Home"
      - text: "{{< iconify ic outline-category >}} Research Themes"
        menu:
        - text: "{{< iconify twemoji rat >}} Lassa Fever"
          href: lassa.qmd
        - text: "{{< fa virus >}} Monkeypox"
          href: monkeypox.qmd
        - text: "{{< fa lungs-virus >}} COVID-19"
          href: covid_19.qmd
        - text: "{{< fa bacterium >}} Antimicrobial Resistance (AMR)"
          href: amr.qmd
        - href: others.qmd
          text: "{{< fa shuffle >}} Other Work"
      - href: https://scholar.google.com/citations?user=fT8u5MwAAAAJ&hl=en
        text: "{{< iconify ooui articles-ltr >}} Publications"
    right:
      - href: about.qmd
        text: "About me"
      - icon: twitter
        href: https://twitter.com/David_Simons_UK
        aria-label: David Twitter
      - icon: github
        href: https://github.com/DidDrog11
        aria-label: David GitHub
    sidebar:
    - title: "Lassa Fever"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - lassa.qmd
        - lassa/rodent_trapping.qmd
        - lassa/rodent_review.qmd
        - lassa/lips.qmd
    
format:
  html:
    theme: pulse
    toc: true
    toc-depth: 3
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.dsimons\.org\/'

comments:
  hypothesis: 
    theme: clean
    
execute:
  freeze: auto