project:
  type: website
  render:
    - "*.qmd"           
    - "!cv.qmd"         
    - "amr/"          
    - "arha/"
    - "covid/"
    - "images/"
    - "lassa/"          
    - "monkeypox/"
    - "open_science/"   # Added to ensure the new child pages render
    - "policy/"
    - "others/"
    - "rodent_ecology/"

website:
  title: "David Simons"
  favicon: /images/icon.ico
  open-graph: true
  twitter-card: true
  google-analytics: "G-Z4H9BE4MVE"
  page-navigation: true
  navbar:
    logo: /images/icon.ico
    foreground: light
    background: dark
    search: true
    left:
      - href: index.qmd
        text: "{{< iconify mingcute home-2-line >}} Home"
      - text: "{{< iconify ic outline-category >}} Research Themes"
        menu:
          - text: "Rodent-Borne Zoonoses"
          - text: "{{< iconify twemoji rat >}} Lassa Fever"
            href: lassa.qmd
          - text: "{{< iconify ph bug-bold >}} Project ArHa"
            href: arha.qmd
          - text: "{{< iconify fa6-solid bugs >}} Rodent Ecology"
            href: rodent_ecology.qmd
          - text: "{{< iconify mdi open-source-initiative >}} Open Science & Data"
            href: open_science.qmd
          - text: "{{< iconify mdi file-document-edit >}} Strategy & Policy"
            href: policy.qmd
          - text: "---"
          - text: "Other Major Themes"
          - text: "{{< fa virus >}} Monkeypox"
            href: monkeypox.qmd
          - text: "{{< fa lungs-virus >}} COVID-19"
            href: covid_19.qmd
          - text: "{{< fa bacterium >}} Antimicrobial Resistance (AMR)"
            href: amr.qmd
          - text: "---"
          - href: others.qmd
            text: "{{< fa shuffle >}} Other Work"
      - href: https://scholar.google.com/citations?user=fT8u5MwAAAAJ&hl=en
        text: "{{< iconify ooui articles-ltr >}} Publications"
      - href: consultancy.qmd
        text: "{{< iconify mdi briefcase-outline >}} Consultancy"
    right:
      - href: about.qmd
        text: "About me"
      - icon: bluesky
        href: https://bsky.app/profile/davidsimons.bsky.social
        aria-label: David Bluesky
      - icon: github
        href: https://github.com/DidDrog11
        aria-label: David GitHub

format:
  html:
    theme: pulse
    toc: true
    toc-depth: 3
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.dsimons\.org\/'

comments:
  hypothesis: 
    theme: clean
    
execute:
  freeze: auto